name: commit-validation
on: [push, pull_request, workflow_dispatch]

jobs:
  check-validation:
    runs-on: ${{ vars.ARC_TINY_NAME_PRIMARY }}
    timeout-minutes: 5
    name: Check commit signing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check commit
        uses: PopcornPalace/commit-validation-action@main
        id: check-commit
      - name: Show check-commit
        run: echo "${{ steps.check-commit.outputs.commit }}"
