on:
  push:
    branches:
      - main
  schedule:
    # Once a week on Saturday 00:00
    - cron: '0 0 * * 1'

jobs:
  audit_log:
    runs-on: ubuntu-latest
    name: Membership Audit Log
    steps:
      - name: Get Git Audit Log for Repos
        uses: nicklegan/github-org-git-audit-log-for-repos-action@v1.1.1
        with:
          token: ${{ secrets.ORG_TOKEN }}
          fromdate: ${{ github.event.inputs.fromdate }} # Used for workflow dispatch input
          todate: ${{ github.event.inputs.todate }} # Used for workflow dispatch input
